### ISSUE TITLE
Inquiry About Slow Performance of BOCPD on Our Dataset

### ISSUE THREAD

**Issue by beifangqiuer** [phamquiluan/baro#14]
I am currently working on anomaly detection using the BOCPD (Bayesian Online Change Point Detection) method on our dataset, which consists of approximately 7,000 rows and 26 columns. However, I have encountered an issue with the process being extremely slow, and I'm not sure why this is happening.

I would appreciate any insights or suggestions you might have regarding the potential causes of this slowdown and how I might be able to optimize the performance.

Thank you for your assistance.

Best regards,

**Comment by phamquiluan** [comment]
>  7,000 rows and 26 columns

Omg @beifangqiuer, BOCPD is really slow compared to other methods since it takes into account the dependency of multivariate time series.

You can try to reduce the number of time series (reduce 26 columns to 3-4 columns), and re-sampling the data (reduce 7000 rows to 700 rows). 

I also offer nsigma for anomaly detection, you can also give it a try: https://github.com/phamquiluan/baro/blob/main/baro/anomaly_detection.py#L7
